Update 2

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,61 +1,86 @@
-name: Publish to CurseForge
+name: Build and Publish WoWThreads
 
 on:
   push:
     branches:
       - main
-  workflow_dispatch:
 
 jobs:
-  package:
+  build:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Checkout repository
-        uses: actions/checkout@v2
+    - name: Checkout code
+      uses: actions/checkout@v2
 
-      - name: Package files
-        run: |
-          mkdir -p package/WoWThreads
-          cp -r Docs package/WoWThreads/
-          cp -r Libs package/WoWThreads/
-          cp -r Locales package/WoWThreads/
-          cp -r Sources package/WoWThreads/
-          cp LICENSE package/WoWThreads/
-          cp README.md package/WoWThreads/
-          cp WoWThreads.code-workspace package/WoWThreads/
-          cp WoWThreads_Cata.toc package/WoWThreads/
-          cp WoWThreads_Mainline.toc package/WoWThreads/
-          cp WoWThreads_Vanilla.toc package/WoWThreads/
-          cd package
-          zip -r ../WoWThreads.zip WoWThreads
+    - name: Set up Node.js
+      uses: actions/setup-node@v2
+      with:
+        node-version: '14'
 
-      - name: Upload artifact
-        uses: actions/upload-artifact@v2
-        with:
-          name: WoWThreads
-          path: WoWThreads.zip
+    - name: Install dependencies
+      run: npm install
+
+    - name: Build the project
+      run: npm run build
+
+    - name: Package WoWThreads
+      run: |
+        mkdir -p package/WoWThreads
+        cp -r Docs package/WoWThreads/
+        cp -r Libs package/WoWThreads/
+        cp -r Locales package/WoWThreads/
+        cp -r Sources package/WoWThreads/
+        cp LICENSE package/WoWThreads/
+        cp README.md package/WoWThreads/
+        cp WoWThreads.code-workspace package/WoWThreads/
+        cp WoWThreads_Cata.toc package/WoWThreads/
+        cp WoWThreads_Mainline.toc package/WoWThreads/
+        cp WoWThreads_Vanilla.toc package/WoWThreads/
+        cd package
+        zip -r ../WoWThreads.zip WoWThreads
+
+    - name: Upload Artifact
+      uses: actions/upload-artifact@v2
+      with:
+        name: WoWThreads
+        path: WoWThreads.zip
 
   publish:
-    needs: package
     runs-on: ubuntu-latest
+    needs: build
 
     steps:
-      - name: Download build artifact
-        uses: actions/download-artifact@v2
-        with:
-          name: WoWThreads
-          path: ./WoWThreads
+    - name: Download build artifact
+      uses: actions/download-artifact@v2
+      with:
+        name: WoWThreads
 
-      - name: Rename downloaded directory to ZIP
-        run: |
-          mv WoWThreads/WoWThreads.zip WoWThreads.zip
+    - name: Move artifact
+      run: mv WoWThreads/WoWThreads.zip WoWThreads.zip
 
-      - name: Print working directory
-        run: pwd
+    - name: Check existence of ZIP file
+      run: |
+        if [ -f "WoWThreads.zip" ]; then echo "File exists"; else echo "File does not exist"; fi
 
-      - name: List files in working directory
-        run: ls -la
+    - name: Publish to CurseForge
+      env:
+        CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
+        CURSEFORGE_EMAIL: ${{ secrets.CURSEFORGE_EMAIL }}
+      run: |
+        response=$(curl -s -w "%{http_code}" -X POST "https://wow.curseforge.com/api/projects/1062198/upload-file" \
+        -H "x-api-token: $CURSEFORGE_API_KEY" \
+        -F "file=@WoWThreads.zip" \
+        -F "metadata=<metadata.json" -o response.json)
+        http_code=$(tail -n1 <<< "$response")
+        content=$(sed '$d' <<< "$response")
 
-      - name: Check existence of ZIP file
-        run: |
+        echo "HTTP Status Code: $http_code"
+        echo "Response Content: $content"
+
+        if [ "$http_code" -ne 200 ]; then
+          echo "Upload failed with status code $http_code"
+          exit 1
+        else
+          echo "Upload succeeded"
+        fi
