Removed Cata, Vanilla, and Mainline .toc files

diff --git a/.github/workflows/Create-release.yml b/.github/workflows/Create-release.yml
--- a/.github/workflows/Create-release.yml
+++ b/.github/workflows/Create-release.yml
@@ -16,7 +16,15 @@ jobs:
 
       - name: Retrieve version
         id: get_version
-        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
+        run: |
+          if [ ! -f VERSION ]; then
+            echo "VERSION file not found!"
+            exit 1
+          fi
+          echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
+
+      - name: Clean up previous builds
+        run: rm -rf WoWThreads.zip package
 
       - name: Package files 
         run: |
@@ -27,11 +35,8 @@ jobs:
           cp -r Sources package/WoWThreads/
           cp LICENSE package/WoWThreads/
           cp README.md package/WoWThreads/
-          cp WoWThreads_Cata.toc package/WoWThreads/
-          cp WoWThreads_Mainline.toc package/WoWThreads/
-          cp WoWThreads_Vanilla.toc package/WoWThreads/
           cd package
-          zip -r ../WoWThreads.zip WoWThreads
+          zip -r ../WoWThreads.zip WoWThreads || { echo 'Zip creation failed'; exit 1; }
 
       - name: Install GitHub CLI 
         run: |
@@ -43,10 +48,18 @@ jobs:
             sudo dpkg -i gh_2.20.2_linux_amd64.deb
             sudo apt-get install -f -y
           }
+          gh version
 
       - name: Authenticate GitHub CLI
         run: |
           echo "${{ secrets.PERSONAL_ACCESS_TOKEN }}" | gh auth login --with-token
+
+      - name: Check if Release Exists
+        run: |
+          if gh release view "v${{ env.VERSION }}"; then
+            echo "Release already exists for v${{ env.VERSION }}"
+            exit 1
+          fi
 
       - name: Create Release
         run: |
@@ -56,5 +69,6 @@ jobs:
           gh release create $tag_name WoWThreads.zip --title "$release_name" --notes "$release_body"
 
       - name: List release files for verification
+        if: success()
         run: |
           gh release view "v${{ env.VERSION }}"
